// lib/orientation/role-intelligence.ts
// Comprehensive Role Intelligence System for Orientation
// Contains 45+ authentic job roles with real-world data

export type DifficultyLevel = "beginner" | "intermediate" | "advanced" | "expert";
export type DemandLevel = "high" | "medium" | "low";
export type WorkStyle = "creative" | "analytical" | "systems" | "collaborative";
export type CognitiveType = "Builder" | "Analytical" | "Creative" | "Systems";

export interface Role {
  id: string;
  name: string;
  domain: string;
  subdomain: string;
  description: string;
  dailyWork: string;
  requiredSkills: string[];
  optionalSkills: string[];
  difficulty: DifficultyLevel;
  demandLevel: DemandLevel;
  salaryRangeIndia: {
    junior: string; // 0-2 years
    mid: string; // 2-5 years
    senior: string; // 5+ years
  };
  growthPath: string[];
  workStyle: WorkStyle[];
  learningCurve: "steep" | "moderate" | "gradual";
  remoteFreundly: boolean;
  whyTake: string;
  challenges: string;
  cognitiveAlignment: CognitiveType[];
}

const ROLES: Role[] = [
  // ====== SOFTWARE ENGINEERING (11 roles) ======
  {
    id: "backend-engineer",
    name: "Backend Engineer",
    domain: "Software Engineering",
    subdomain: "Server-side Development",
    description: "Design, build, and maintain server-side systems that power applications. Focus on APIs, databases, and system architecture.",
    dailyWork: "Write backend code in Python/Node.js/Java, design REST/GraphQL APIs, optimize database queries, review pull requests, troubleshoot production issues, participate in architecture decisions.",
    requiredSkills: [
      "Server-side Language (Python/Node.js/Java/Go)",
      "Database Design (SQL/NoSQL)",
      "API Design (REST/GraphQL)",
      "System Design Basics",
      "Git & Version Control",
    ],
    optionalSkills: [
      "Microservices Architecture",
      "Message Queues (RabbitMQ/Kafka)",
      "Docker & Kubernetes",
      "AWS/GCP/Azure",
    ],
    difficulty: "intermediate",
    demandLevel: "high",
    salaryRangeIndia: {
      junior: "₹5-8 LPA",
      mid: "₹12-20 LPA",
      senior: "₹25-45 LPA",
    },
    growthPath: ["Staff Engineer", "Engineering Manager", "Architect", "CTO"],
    workStyle: ["analytical", "systems"],
    learningCurve: "moderate",
    remoteFreundly: true,
    whyTake: "Backend powers everything. Deep problem-solving, system-level impact, stable career with high demand.",
    challenges: "Debugging production issues under pressure, dealing with legacy systems, scaling complexity exponentially.",
    cognitiveAlignment: ["Systems", "Analytical"],
  },

  {
    id: "frontend-engineer",
    name: "Frontend Engineer",
    domain: "Software Engineering",
    subdomain: "Client-side Development",
    description: "Build user interfaces and client-side applications. Create responsive designs, manage state, optimize performance.",
    dailyWork: "Write React/Vue/Angular code, design responsive UIs, optimize performance, implement animations, collaborate with designers, fix browser compatibility issues.",
    requiredSkills: [
      "JavaScript/TypeScript",
      "React/Vue/Angular",
      "CSS & Responsive Design",
      "DOM Manipulation",
      "Git & Version Control",
    ],
    optionalSkills: [
      "Next.js/Nuxt",
      "Tailwind CSS",
      "Web Performance Optimization",
      "Testing (Jest/Cypress)",
      "Webpack/Vite",
    ],
    difficulty: "beginner",
    demandLevel: "high",
    salaryRangeIndia: {
      junior: "₹4-6 LPA",
      mid: "₹10-16 LPA",
      senior: "₹20-35 LPA",
    },
    growthPath: ["Senior Frontend", "Frontend Architect", "Tech Lead", "Product Manager"],
    workStyle: ["creative", "collaborative"],
    learningCurve: "gradual",
    remoteFreundly: true,
    whyTake: "Immediate visual feedback, creative problem-solving, fast learning curve, high demand.",
    challenges: "Browser compatibility nightmares, managing complex state, performance optimization under constraints.",
    cognitiveAlignment: ["Creative", "Builder"],
  },

  {
    id: "fullstack-engineer",
    name: "Full Stack Engineer",
    domain: "Software Engineering",
    subdomain: "End-to-End Development",
    description: "Build complete applications from frontend to backend. Own features end-to-end.",
    dailyWork: "Design databases, build APIs, create UIs, deploy applications, manage infrastructure basics, troubleshoot full-stack issues.",
    requiredSkills: [
      "Frontend Stack (React/Vue)",
      "Backend Stack (Node.js/Python)",
      "Database Design",
      "Version Control",
      "Basic DevOps (Docker)",
    ],
    optionalSkills: [
      "Next.js/Full-stack Frameworks",
      "AWS Basics",
      "Testing across layers",
      "System Design",
    ],
    difficulty: "intermediate",
    demandLevel: "high",
    salaryRangeIndia: {
      junior: "₹5-8 LPA",
      mid: "₹13-22 LPA",
      senior: "₹28-50 LPA",
    },
    growthPath: ["Tech Lead", "Engineering Manager", "Architect", "Startup Founder"],
    workStyle: ["systems", "collaborative"],
    learningCurve: "steep",
    remoteFreundly: true,
    whyTake: "Maximum autonomy, end-to-end ownership, valuable across company sizes, startup-ready.",
    challenges: "Wearing many hats, shallow expertise risk, context switching fatigue.",
    cognitiveAlignment: ["Builder", "Systems"],
  },

  {
    id: "mobile-engineer-ios",
    name: "iOS Mobile Engineer",
    domain: "Software Engineering",
    subdomain: "Mobile Development",
    description: "Develop applications for iOS using Swift and SwiftUI. Focus on native performance and platform conventions.",
    dailyWork: "Write Swift code, design native UIs with SwiftUI, integrate with backend APIs, debug on physical devices, manage App Store submissions.",
    requiredSkills: [
      "Swift",
      "SwiftUI (or UIKit)",
      "iOS Architecture Patterns",
      "Xcode",
      "REST API Integration",
    ],
    optionalSkills: [
      "Core Data",
      "Push Notifications",
      "In-app Payments",
      "App Analytics",
      "TestFlight",
    ],
    difficulty: "intermediate",
    demandLevel: "high",
    salaryRangeIndia: {
      junior: "₹6-9 LPA",
      mid: "₹14-22 LPA",
      senior: "₹30-48 LPA",
    },
    growthPath: ["Senior iOS", "iOS Architect", "Tech Lead", "Engineering Manager"],
    workStyle: ["creative", "systems"],
    learningCurve: "moderate",
    remoteFreundly: true,
    whyTake: "Premium market, steady demand from Apple ecosystem, high salaries, loyal user base.",
    challenges: "Rapid iOS version updates, Apple's strict guidelines, fragmentation across devices.",
    cognitiveAlignment: ["Builder", "Systems"],
  },

  {
    id: "mobile-engineer-android",
    name: "Android Mobile Engineer",
    domain: "Software Engineering",
    subdomain: "Mobile Development",
    description: "Develop applications for Android using Kotlin. Handle multiple device configurations and Android versions.",
    dailyWork: "Write Kotlin code, build Android UIs with Jetpack Compose, integrate backend APIs, test on various devices, manage Google Play Store.",
    requiredSkills: [
      "Kotlin",
      "Android Framework",
      "Jetpack Compose (or XML layouts)",
      "Android Studio",
      "REST API Integration",
    ],
    optionalSkills: [
      "Room Database",
      "WorkManager",
      "Firebase",
      "Performance Profiling",
      "NDK (C++)",
    ],
    difficulty: "intermediate",
    demandLevel: "high",
    salaryRangeIndia: {
      junior: "₹5-8 LPA",
      mid: "₹12-20 LPA",
      senior: "₹28-45 LPA",
    },
    growthPath: ["Senior Android", "Android Architect", "Tech Lead", "Engineering Manager"],
    workStyle: ["analytical", "systems"],
    learningCurve: "moderate",
    remoteFreundly: true,
    whyTake: "Massive market share (70%+), diverse device ecosystem, growing demand, India is major hub.",
    challenges: "Fragmentation across devices/OS versions, slower development than web, Java ecosystem complexity.",
    cognitiveAlignment: ["Builder", "Systems"],
  },

  {
    id: "devops-engineer",
    name: "DevOps Engineer",
    domain: "Software Engineering",
    subdomain: "Infrastructure & Deployment",
    description: "Manage infrastructure, CI/CD pipelines, deployment automation, and system reliability. Bridge between development and operations.",
    dailyWork: "Design cloud infrastructure, write Infrastructure-as-Code, build CI/CD pipelines, monitor systems, handle deployments, troubleshoot production issues.",
    requiredSkills: [
      "Linux/Unix Administration",
      "Docker & Kubernetes",
      "Bash Scripting",
      "Cloud Platform (AWS/GCP/Azure)",
      "CI/CD Tools (Jenkins/GitLab CI)",
    ],
    optionalSkills: [
      "Terraform",
      "Prometheus & Grafana",
      "ELK Stack",
      "HashiCorp Tools",
      "Python Scripting",
    ],
    difficulty: "advanced",
    demandLevel: "high",
    salaryRangeIndia: {
      junior: "₹6-10 LPA",
      mid: "₹15-25 LPA",
      senior: "₹35-60 LPA",
    },
    growthPath: ["Senior DevOps", "DevOps Architect", "SRE Manager", "Director of Engineering"],
    workStyle: ["systems", "analytical"],
    learningCurve: "steep",
    remoteFreundly: true,
    whyTake: "Critical to every company, high responsibility, excellent salaries, on-call premium pays well.",
    challenges: "On-call stress at 3 AM, dealing with production fires, learning curve is steep, burnout risk.",
    cognitiveAlignment: ["Systems", "Analytical"],
  },

  {
    id: "embedded-engineer",
    name: "Embedded Systems Engineer",
    domain: "Software Engineering",
    subdomain: "Hardware-close Programming",
    description: "Write low-level code for microcontrollers, IoT devices, and hardware. Optimize for resource constraints.",
    dailyWork: "Write C/C++ for embedded systems, debug hardware interfaces, optimize memory usage, work with oscilloscopes, test on physical devices.",
    requiredSkills: [
      "C/C++",
      "Microcontroller Basics (ARM/AVR)",
      "Hardware Debugging",
      "Serial Protocols (I2C/SPI/UART)",
      "Firmware Development",
    ],
    optionalSkills: [
      "RTOS",
      "Assembly",
      "IoT Protocols (MQTT/BLE)",
      "PCB Design Basics",
      "Power Management",
    ],
    difficulty: "expert",
    demandLevel: "medium",
    salaryRangeIndia: {
      junior: "₹5-8 LPA",
      mid: "₹12-20 LPA",
      senior: "₹28-45 LPA",
    },
    growthPath: ["Senior Embedded", "Firmware Architect", "Hardware Engineer", "CTO"],
    workStyle: ["analytical", "systems"],
    learningCurve: "steep",
    remoteFreundly: false,
    whyTake: "Niche skill with high value, deep technical mastery, IoT demand growing, problem-solving satisfaction.",
    challenges: "Steep learning curve, hardware debugging is hard, slow iteration cycles, niche market.",
    cognitiveAlignment: ["Systems", "Analytical"],
  },

  {
    id: "qa-engineer",
    name: "QA Engineer",
    domain: "Software Engineering",
    subdomain: "Quality Assurance",
    description: "Ensure software quality through testing, automation, and process improvement. Catch bugs before users do.",
    dailyWork: "Write test plans, manual testing, build automation frameworks, report bugs, work with developers, track test coverage, improve quality metrics.",
    requiredSkills: [
      "Testing Fundamentals (Manual/Automated)",
      "Test Automation Framework (Selenium/Cypress)",
      "SQL for DB Testing",
      "Python/Java",
      "API Testing (Postman)",
    ],
    optionalSkills: [
      "Performance Testing (JMeter)",
      "CI/CD Integration",
      "BDD Testing (Cucumber)",
      "Security Testing",
      "Mobile Testing",
    ],
    difficulty: "beginner",
    demandLevel: "high",
    salaryRangeIndia: {
      junior: "₹4-6 LPA",
      mid: "₹9-15 LPA",
      senior: "₹18-30 LPA",
    },
    growthPath: ["Senior QA", "QA Lead", "Engineering Manager", "Quality Director"],
    workStyle: ["analytical", "systems"],
    learningCurve: "gradual",
    remoteFreundly: true,
    whyTake: "Low entry barrier, good career progression, prevents production disasters, respected role.",
    challenges: "Perception as 'less technical', repetitive manual testing, automation complexity, catching all bugs is impossible.",
    cognitiveAlignment: ["Analytical", "Systems"],
  },

  {
    id: "solutions-architect",
    name: "Solutions Architect",
    domain: "Software Engineering",
    subdomain: "Architecture & Strategy",
    description: "Design end-to-end solutions for clients. Bridge between business needs and technical implementation.",
    dailyWork: "Gather requirements, design system architecture, create technical specifications, present to clients, oversee implementation, manage technical risks.",
    requiredSkills: [
      "System Design",
      "Cloud Architecture",
      "Enterprise Patterns",
      "Business Acumen",
      "Communication",
      "5+ years development experience",
    ],
    optionalSkills: [
      "Cloud Certifications (AWS/Azure)",
      "Process Modeling",
      "Project Management",
      "Budget Management",
    ],
    difficulty: "advanced",
    demandLevel: "high",
    salaryRangeIndia: {
      junior: "N/A",
      mid: "₹20-35 LPA",
      senior: "₹40-80 LPA",
    },
    growthPath: ["Principal Architect", "VP Engineering", "CTO", "Founder"],
    workStyle: ["systems", "collaborative"],
    learningCurve: "steep",
    remoteFreundly: true,
    whyTake: "High visibility, strategic impact, excellent salaries, leadership opportunity, client interaction.",
    challenges: "Political navigation, managing stakeholder expectations, being wrong is costly, decision paralysis.",
    cognitiveAlignment: ["Systems", "Analytical"],
  },

  {
    id: "game-dev-engineer",
    name: "Game Developer",
    domain: "Software Engineering",
    subdomain: "Game Development",
    description: "Create games using engines like Unity or Unreal. Balance gameplay, performance, and fun.",
    dailyWork: "Write gameplay code, optimize performance, implement game logic, fix bugs, collaborate with designers, test on target platforms.",
    requiredSkills: [
      "C# (Unity) or C++ (Unreal)",
      "Game Engine (Unity/Unreal)",
      "3D Math & Physics",
      "Game Loops & Event Systems",
      "Performance Optimization",
    ],
    optionalSkills: [
      "Graphics Programming",
      "Networking (Multiplayer)",
      "Audio Integration",
      "Mobile Optimization",
      "VR Development",
    ],
    difficulty: "advanced",
    demandLevel: "medium",
    salaryRangeIndia: {
      junior: "₹5-8 LPA",
      mid: "₹12-20 LPA",
      senior: "₹25-45 LPA",
    },
    growthPath: ["Senior Game Dev", "Technical Director", "Gameplay Lead", "Game Director"],
    workStyle: ["creative", "systems"],
    learningCurve: "steep",
    remoteFreundly: true,
    whyTake: "Creative outlet, gaming is passion, potential indie success, global market, fun tech.",
    challenges: "Risky careers (game closures), crunch culture common, monetization pressure, smaller community.",
    cognitiveAlignment: ["Creative", "Builder"],
  },

  // ====== DATA & AI (11 roles) ======
  {
    id: "data-engineer",
    name: "Data Engineer",
    domain: "Data & AI",
    subdomain: "Data Infrastructure",
    description: "Build pipelines and systems to collect, transform, and store data at scale. Enable analytics and ML.",
    dailyWork: "Design data pipelines, write ETL jobs, optimize data storage, manage data quality, monitor pipelines, troubleshoot data issues.",
    requiredSkills: [
      "SQL",
      "Python/Scala",
      "Big Data Tools (Spark/Hadoop)",
      "Cloud Data Warehouses (Snowflake/BigQuery)",
      "Distributed Systems Basics",
    ],
    optionalSkills: [
      "Apache Airflow/Prefect",
      "Data Modeling",
      "Stream Processing (Kafka)",
      "dbt",
      "Data Quality Tools",
    ],
    difficulty: "intermediate",
    demandLevel: "high",
    salaryRangeIndia: {
      junior: "₹6-10 LPA",
      mid: "₹15-25 LPA",
      senior: "₹35-60 LPA",
    },
    growthPath: ["Senior Data Engineer", "Data Architect", "Engineering Lead", "Director of Data"],
    workStyle: ["analytical", "systems"],
    learningCurve: "moderate",
    remoteFreundly: true,
    whyTake: "Data is 'new oil', critical infrastructure, high demand, good scaling, emerging tech.",
    challenges: "Complex debugging, data quality nightmares, system design complexity, silent failures.",
    cognitiveAlignment: ["Systems", "Analytical"],
  },

  {
    id: "data-analyst",
    name: "Data Analyst",
    domain: "Data & AI",
    subdomain: "Analytics",
    description: "Analyze data to uncover insights and drive business decisions. Use SQL and visualization tools.",
    dailyWork: "Write SQL queries, create dashboards, analyze trends, present findings to stakeholders, find business opportunities, A/B test analysis.",
    requiredSkills: [
      "SQL",
      "Excel/Google Sheets",
      "BI Tools (Tableau/Looker/Power BI)",
      "Statistics Basics",
      "Business Acumen",
    ],
    optionalSkills: [
      "Python/R for Analysis",
      "Data Visualization",
      "Experimentation Design",
      "Financial Analysis",
    ],
    difficulty: "beginner",
    demandLevel: "high",
    salaryRangeIndia: {
      junior: "₹4-6 LPA",
      mid: "₹10-16 LPA",
      senior: "₹20-35 LPA",
    },
    growthPath: ["Senior Analyst", "Analytics Lead", "Product Manager", "Chief Data Officer"],
    workStyle: ["analytical", "collaborative"],
    learningCurve: "gradual",
    remoteFreundly: true,
    whyTake: "Low entry barrier, immediate business impact, storytelling with data, well-paying, hybrid role.",
    challenges: "Politics & stakeholder management, data quality issues, perfectionism trap, metrics gaming.",
    cognitiveAlignment: ["Analytical", "Builder"],
  },

  {
    id: "ml-engineer",
    name: "Machine Learning Engineer",
    domain: "Data & AI",
    subdomain: "AI/ML",
    description: "Build and deploy machine learning models that solve real-world problems. Bridge research and production.",
    dailyWork: "Explore data, train models, evaluate performance, optimize hyperparameters, deploy to production, monitor model drift, handle retraining.",
    requiredSkills: [
      "Python",
      "ML Frameworks (TensorFlow/PyTorch/Scikit-learn)",
      "Statistics & ML Theory",
      "SQL",
      "Linux Basics",
    ],
    optionalSkills: [
      "Deep Learning",
      "Computer Vision / NLP",
      "MLOps (MLflow/Kubeflow)",
      "Feature Engineering",
      "Experiment Tracking",
    ],
    difficulty: "advanced",
    demandLevel: "high",
    salaryRangeIndia: {
      junior: "₹7-12 LPA",
      mid: "₹18-30 LPA",
      senior: "₹40-70 LPA",
    },
    growthPath: ["Senior ML Engineer", "ML Research Engineer", "ML Architect", "AI Director"],
    workStyle: ["analytical", "creative"],
    learningCurve: "steep",
    remoteFreundly: true,
    whyTake: "Cutting-edge technology, highest salaries, solving hard problems, AI is future, research interesting.",
    challenges: "Very high bar (academic background needed), experimentation is slow, math-heavy, overhype vs reality gap.",
    cognitiveAlignment: ["Analytical", "Systems"],
  },

  {
    id: "data-scientist",
    name: "Data Scientist",
    domain: "Data & AI",
    subdomain: "Analytics & AI",
    description: "Use statistical analysis and machine learning to extract insights and build predictive models. Mix of analysis and ML.",
    dailyWork: "Define hypotheses, analyze datasets, build statistical models, create dashboards, present insights, mentor junior analysts.",
    requiredSkills: [
      "Python",
      "SQL",
      "Statistics",
      "Data Visualization",
      "ML Basics",
      "Excel/Spreadsheets",
    ],
    optionalSkills: [
      "Advanced ML",
      "Causal Inference",
      "Experiment Design",
      "Deep Learning",
      "Domain expertise",
    ],
    difficulty: "intermediate",
    demandLevel: "high",
    salaryRangeIndia: {
      junior: "₹6-9 LPA",
      mid: "₹15-25 LPA",
      senior: "₹30-50 LPA",
    },
    growthPath: ["Senior Data Scientist", "Principal Scientist", "Analytics Manager", "VP of Analytics"],
    workStyle: ["analytical", "creative"],
    learningCurve: "steep",
    remoteFreundly: true,
    whyTake: "Problem-solving focused, business impact driven, good salary, analytics + ML hybrid, research opportunity.",
    challenges: "Ambiguous problems, poor data quality, insights not applied, politics, job title inflation.",
    cognitiveAlignment: ["Analytical", "Creative"],
  },

  {
    id: "llm-engineer",
    name: "LLM/GenAI Engineer",
    domain: "Data & AI",
    subdomain: "AI/ML",
    description: "Specialize in Large Language Models and Generative AI. Build applications and optimize model performance.",
    dailyWork: "Fine-tune LLMs, build RAG systems, prompt engineering, integrate LLM APIs, evaluate model outputs, optimize costs/latency.",
    requiredSkills: [
      "Python",
      "LLM APIs (OpenAI/anthropic/Cohere)",
      "Prompt Engineering",
      "Vector Databases (Pinecone/Weaviate)",
      "RAG Basics",
    ],
    optionalSkills: [
      "Fine-tuning LLMs",
      "RLHF",
      "Quantization",
      "LLM Evaluation",
      "LangChain/LlamaIndex",
    ],
    difficulty: "advanced",
    demandLevel: "high",
    salaryRangeIndia: {
      junior: "₹8-12 LPA",
      mid: "₹20-35 LPA",
      senior: "₹45-80 LPA",
    },
    growthPath: ["Senior LLM Engineer", "AI Product Lead", "Research Scientist", "AI Director"],
    workStyle: ["analytical", "creative"],
    learningCurve: "moderate",
    remoteFreundly: true,
    whyTake: "Cutting-edge, hottest field now, highest salaries, AI explosion, every company needs this.",
    challenges: "Rapidly evolving (changes weekly), token costs spiral, hallucinations hard to fix, research-heavy.",
    cognitiveAlignment: ["Analytical", "Creative"],
  },

  {
    id: "analytics-engineer",
    name: "Analytics Engineer",
    domain: "Data & AI",
    subdomain: "Data Infrastructure",
    description: "Build data systems and tools for analytics teams. Mix of engineering and analytics with focus on clean data.",
    dailyWork: "Build data models (dbt), design analytics infrastructure, create reusable metrics, write SQL, mentor analysts, improve data quality.",
    requiredSkills: [
      "SQL (Advanced)",
      "dbt",
      "Data Warehousing",
      "Python/Scripting",
      "Git/Version Control",
    ],
    optionalSkills: [
      "Spark",
      "Data Modeling",
      "BI Tools",
      "Cloud Data Platforms",
      "Cube.js or Metrics Layer",
    ],
    difficulty: "intermediate",
    demandLevel: "high",
    salaryRangeIndia: {
      junior: "₹5-8 LPA",
      mid: "₹12-20 LPA",
      senior: "₹25-40 LPA",
    },
    growthPath: ["Senior Analytics Engineer", "Data Lead", "Analytics Manager", "Chief Data Officer"],
    workStyle: ["analytical", "systems"],
    learningCurve: "moderate",
    remoteFreundly: true,
    whyTake: "Emerging role with high demand, enables whole team, data quality focus, good work-life balance.",
    challenges: "Stakeholder communication, perfectionism in data quality, dbt learning curve, newer field = less guidance.",
    cognitiveAlignment: ["Systems", "Analytical"],
  },

  {
    id: "ml-ops-engineer",
    name: "ML Ops Engineer",
    domain: "Data & AI",
    subdomain: "Infrastructure",
    description: "Manage ML model lifecycle from development to production. Ensure ML systems are reliable and efficient.",
    dailyWork: "Build ML pipelines, deploy models, monitor performance, handle model versioning, optimize inference, manage ML infrastructure.",
    requiredSkills: [
      "ML Fundamentals",
      "Python",
      "Docker & Kubernetes",
      "ML Frameworks",
      "GitOps",
    ],
    optionalSkills: [
      "Kubernetes",
      "Feature Stores (Tecton)",
      "Model Registries",
      "Monitoring & Observability",
      "CI/CD for ML",
    ],
    difficulty: "advanced",
    demandLevel: "high",
    salaryRangeIndia: {
      junior: "₹7-11 LPA",
      mid: "₹16-28 LPA",
      senior: "₹35-60 LPA",
    },
    growthPath: ["Senior MLOps", "MLOps Lead", "Platform Engineer", "VP of Platform"],
    workStyle: ["systems", "analytical"],
    learningCurve: "steep",
    remoteFreundly: true,
    whyTake: "Combine ML + DevOps (best of both), critical infrastructure, high responsibility, growing demand, emerging role.",
    challenges: "ML is unpredictable (vs traditional software), tools landscape is chaotic, steep learning curve, emerging best practices.",
    cognitiveAlignment: ["Systems", "Analytical"],
  },

  {
    id: "business-analyst",
    name: "Business Analyst",
    domain: "Data & AI",
    subdomain: "Analytics",
    description: "Bridge business and technical teams. Analyze processes, identify inefficiencies, drive improvement projects.",
    dailyWork: "Gather requirements, analyze business processes, create dashboards for stakeholders, recommend improvements, manage project requirements.",
    requiredSkills: [
      "Business Process Analysis",
      "SQL",
      "Excel",
      "Stakeholder Communication",
      "Documentation",
    ],
    optionalSkills: [
      "BI Tools",
      "Project Management",
      "Agile/Scrum",
      "Pricing Analytics",
      "Supply Chain Knowledge",
    ],
    difficulty: "beginner",
    demandLevel: "medium",
    salaryRangeIndia: {
      junior: "₹4-6 LPA",
      mid: "₹9-15 LPA",
      senior: "₹18-30 LPA",
    },
    growthPath: ["Senior BA", "Product Manager", "Business Lead", "Director of Operations"],
    workStyle: ["analytical", "collaborative"],
    learningCurve: "gradual",
    remoteFreundly: true,
    whyTake: "Direct business impact, less technical than 'analyst' roles, good bridge career, stable growth.",
    challenges: "Requirements gathering is hard, scope creep common, sometimes scapegoated, less technical than peers.",
    cognitiveAlignment: ["Analytical", "Builder"],
  },

  // ====== CYBERSECURITY (6 roles) ======
  {
    id: "security-engineer",
    name: "Security Engineer",
    domain: "Cybersecurity",
    subdomain: "Application Security",
    description: "Secure applications and systems. Find and fix vulnerabilities before attackers do.",
    dailyWork: "Review code for security flaws, perform penetration testing, harden systems, implement security controls, respond to incidents, train team.",
    requiredSkills: [
      "Network Security Fundamentals",
      "Common Vulnerabilities (OWASP Top 10)",
      "Linux/Windows Administration",
      "Cryptography Basics",
      "Scripting (Python/Bash)",
    ],
    optionalSkills: [
      "SIEM Tools",
      "Penetration Testing",
      "SSL/TLS",
      "API Security",
      "Incident Response",
    ],
    difficulty: "advanced",
    demandLevel: "high",
    salaryRangeIndia: {
      junior: "₹6-10 LPA",
      mid: "₹15-25 LPA",
      senior: "₹30-50 LPA",
    },
    growthPath: ["Senior Security Engineer", "Security Lead", "Security Architect", "CISO"],
    workStyle: ["analytical", "systems"],
    learningCurve: "steep",
    remoteFreundly: true,
    whyTake: "Critical responsibility, companies pay premium, emerging field with growth, every company needs security.",
    challenges: "Always-on feeling, high stakes (real breaches), adversarial mindset required, burnout risk.",
    cognitiveAlignment: ["Analytical", "Systems"],
  },

  {
    id: "devops-security-engineer",
    name: "DevSecOps Engineer",
    domain: "Cybersecurity",
    subdomain: "Infrastructure Security",
    description: "Integrate security into DevOps. Ensure secure infrastructure and deployment pipelines.",
    dailyWork: "Build secure pipelines, implement IaC security, scan containers, manage secrets, security monitoring, compliance automation.",
    requiredSkills: [
      "DevOps (Docker/Kubernetes)",
      "Security Fundamentals",
      "Infrastructure-as-Code",
      "Scripting",
      "Cloud Security",
    ],
    optionalSkills: [
      "Container Security",
      "Network Security",
      "Threat Modeling",
      "SIEM Tools",
      "Compliance (SOC2/ISO27001)",
    ],
    difficulty: "advanced",
    demandLevel: "high",
    salaryRangeIndia: {
      junior: "₹7-11 LPA",
      mid: "₹17-28 LPA",
      senior: "₹35-60 LPA",
    },
    growthPath: ["Senior DevSecOps", "Security Architect", "VP of Security", "CISO"],
    workStyle: ["systems", "analytical"],
    learningCurve: "steep",
    remoteFreundly: true,
    whyTake: "Combines hot fields (DevOps + Security), high demand, prevent breaches at scale, good growth.",
    challenges: "Steep learning curve, DevOps + Security expertise needed, tools landscape is complex.",
    cognitiveAlignment: ["Systems", "Analytical"],
  },

  {
    id: "threat-analyst",
    name: "Threat Analyst",
    domain: "Cybersecurity",
    subdomain: "Threat Intelligence",
    description: "Monitor threats, analyze incidents, and track threat actors. Provide intelligence to defend systems.",
    dailyWork: "Monitor security logs, analyze incidents, track threat actors, create threat reports, recommend mitigations, coordinate incident response.",
    requiredSkills: [
      "Networking",
      "Linux/Windows",
      "Log Analysis",
      "Malware Analysis Basics",
      "Incident Response",
    ],
    optionalSkills: [
      "SIEM Tools",
      "Threat Intelligence Platforms",
      "Reverse Engineering",
      "Digital Forensics",
      "Honeypots",
    ],
    difficulty: "advanced",
    demandLevel: "medium",
    salaryRangeIndia: {
      junior: "₹5-8 LPA",
      mid: "₹12-20 LPA",
      senior: "₹28-45 LPA",
    },
    growthPath: ["Senior Threat Analyst", "Security Lead", "SOC Manager", "VP of Security"],
    workStyle: ["analytical", "systems"],
    learningCurve: "steep",
    remoteFreundly: false,
    whyTake: "Detective work in tech, real-time incident response, high stakes, emerging threats to tackle.",
    challenges: "On-call stress, dealing with active attacks (stressful), low base salaries, SOC burnout common.",
    cognitiveAlignment: ["Analytical", "Systems"],
  },

  {
    id: "cryptographer",
    name: "Cryptographer",
    domain: "Cybersecurity",
    subdomain: "Cryptography",
    description: "Design and implement cryptographic systems that protect data. Theoretical + practical.",
    dailyWork: "Design cryptographic protocols, implement crypto libraries, analyze crypto security, consult on product security, research emerging threats.",
    requiredSkills: [
      "Advanced Mathematics",
      "Cryptography Theory",
      "C/C++",
      "Number Theory",
      "Formal Verification",
    ],
    optionalSkills: [
      "Post-Quantum Cryptography",
      "Zero-Knowledge Proofs",
      "Blockchain Crypto",
      "Formal Methods",
    ],
    difficulty: "expert",
    demandLevel: "low",
    salaryRangeIndia: {
      junior: "₹8-12 LPA",
      mid: "₹20-35 LPA",
      senior: "₹45-80 LPA",
    },
    growthPath: ["Senior Cryptographer", "Crypto Architect", "Research Lead", "VP of Security"],
    workStyle: ["analytical", "creative"],
    learningCurve: "very steep",
    remoteFreundly: true,
    whyTake: "Niche expertise with premium pay, cutting-edge math, every company needs crypto, intellectual challenges.",
    challenges: "Very high barrier to entry (PhD often expected), niche job market, abstract problems, slow career progression.",
    cognitiveAlignment: ["Analytical", "Systems"],
  },

  {
    id: "compliance-engineer",
    name: "Compliance Engineer",
    domain: "Cybersecurity",
    subdomain: "Compliance",
    description: "Ensure systems meet regulatory requirements (GDPR, SOC2, HIPAA). Bridge legal and technical.",
    dailyWork: "Review systems for compliance, implement controls, manage audits, documentation, security training, handle data requests.",
    requiredSkills: [
      "Compliance Knowledge (GDPR/SOC2/HIPAA)",
      "Technical Fundamentals",
      "Documentation",
      "Process Management",
      "Risk Assessment",
    ],
    optionalSkills: [
      "Regulatory Knowledge",
      "Security Audits",
      "Policy Development",
      "Internal Audit",
    ],
    difficulty: "intermediate",
    demandLevel: "high",
    salaryRangeIndia: {
      junior: "₹5-8 LPA",
      mid: "₹11-18 LPA",
      senior: "₹22-35 LPA",
    },
    growthPath: ["Senior Compliance", "Compliance Lead", "Compliance Director", "Chief Compliance Officer"],
    workStyle: ["analytical", "systems"],
    learningCurve: "moderate",
    remoteFreundly: true,
    whyTake: "Regulatory focus (emerging field), stable career, compliance is non-negotiable, lower bar than pure security.",
    challenges: "Legal complexity, regulation changes constantly, sometimes boring, less 'technical' prestige.",
    cognitiveAlignment: ["Analytical", "Systems"],
  },

  // ====== CLOUD & DEVOPS (3 roles) ======
  {
    id: "cloud-architect",
    name: "Cloud Architect",
    domain: "Cloud & DevOps",
    subdomain: "Cloud Infrastructure",
    description: "Design scalable cloud solutions. Lead migration to cloud and optimize cloud spend.",
    dailyWork: "Design cloud infrastructure, optimize costs, lead migrations, make architectural decisions, review designs, mentor team.",
    requiredSkills: [
      "Cloud Platform (AWS/Azure/GCP)",
      "System Design",
      "Networking",
      "Database Design",
      "Infrastructure-as-Code",
    ],
    optionalSkills: [
      "Cloud Certifications",
      "Cost Optimization",
      "Enterprise Architecture",
      "High Availability Design",
    ],
    difficulty: "advanced",
    demandLevel: "high",
    salaryRangeIndia: {
      junior: "N/A",
      mid: "₹18-30 LPA",
      senior: "₹40-75 LPA",
    },
    growthPath: ["Principal Architect", "VP of Cloud", "CTO", "Founder"],
    workStyle: ["systems", "analytical"],
    learningCurve: "steep",
    remoteFreundly: true,
    whyTake: "Cloud transformation happening, high business impact, excellent salaries, strategic role, future-proof.",
    challenges: "5+ years experience needed, high responsibility, cost optimization never ends, decision fatigue.",
    cognitiveAlignment: ["Systems", "Analytical"],
  },

  {
    id: "sre-engineer",
    name: "Site Reliability Engineer (SRE)",
    domain: "Cloud & DevOps",
    subdomain: "Infrastructure & Reliability",
    description: "Balance development velocity with system reliability. Monitor, alert, and improve production systems.",
    dailyWork: "Design monitoring systems, respond to incidents, perform post-mortems, define SLOs, optimize reliability, develop reliability tools.",
    requiredSkills: [
      "System Administration",
      "Monitoring/Observability",
      "Network Basics",
      "Python/Go Scripting",
      "Linux",
    ],
    optionalSkills: [
      "Incident Management",
      "Chaos Engineering",
      "Cost Optimization",
      "Load Balancing",
      "High Availability",
    ],
    difficulty: "advanced",
    demandLevel: "high",
    salaryRangeIndia: {
      junior: "₹8-12 LPA",
      mid: "₹18-30 LPA",
      senior: "₹40-65 LPA",
    },
    growthPath: ["Senior SRE", "SRE Lead", "Engineering Manager", "VP of Engineering"],
    workStyle: ["systems", "analytical"],
    learningCurve: "steep",
    remoteFreundly: true,
    whyTake: "Hybrid role (Dev + Ops + stability), on-call pays well, real systems impact, high growth demand.",
    challenges: "On-call stress (3 AM pages), production fire pressure, perfectionism trap, sometimes seen as 'not real coding'.",
    cognitiveAlignment: ["Systems", "Analytical"],
  },

  {
    id: "platform-engineer",
    name: "Platform Engineer",
    domain: "Cloud & DevOps",
    subdomain: "Infrastructure",
    description: "Build internal developer platforms that help engineers ship faster. Focus on developer experience.",
    dailyWork: "Design developer platforms, build infrastructure tools, improve CI/CD, manage deployment systems, support developers, reduce friction.",
    requiredSkills: [
      "DevOps Fundamentals",
      "Scripting (Python/Go/Bash)",
      "Container Orchestration",
      "Developer UX",
      "Infrastructure-as-Code",
    ],
    optionalSkills: [
      "Kubernetes Operators",
      "Observability",
      "API Design",
      "Cost Optimization",
      "GitOps",
    ],
    difficulty: "advanced",
    demandLevel: "high",
    salaryRangeIndia: {
      junior: "₹7-11 LPA",
      mid: "₹16-28 LPA",
      senior: "₹35-60 LPA",
    },
    growthPath: ["Senior Platform Engineer", "Platform Lead", "VP of Platform", "CTO"],
    workStyle: ["systems", "collaborative"],
    learningCurve: "steep",
    remoteFreundly: true,
    whyTake: "Developer impact (help 100s of engineers), emerging role, high growth, tools focus, developer empathy.",
    challenges: "Tools are never finished, developer demands are infinite, building for other engineers is hard.",
    cognitiveAlignment: ["Systems", "Builder"],
  },

  // ====== PRODUCT & DESIGN (6 roles) ======
  {
    id: "product-manager",
    name: "Product Manager",
    domain: "Product & Design",
    subdomain: "Product Management",
    description: "Define product vision and strategy. Balance customer needs, business goals, and technical feasibility.",
    dailyWork: "Gather user feedback, define roadmaps, write requirements, review designs, prioritize features, measure impact, communicate strategy.",
    requiredSkills: [
      "Communication & Leadership",
      "Data Analysis",
      "Customer Empathy",
      "Strategic Thinking",
      "Product Sense",
    ],
    optionalSkills: [
      "Technical Fundamentals",
      "Analytics",
      "User Research",
      "A/B Testing",
      "Business Acumen",
    ],
    difficulty: "intermediate",
    demandLevel: "high",
    salaryRangeIndia: {
      junior: "₹8-12 LPA",
      mid: "₹18-30 LPA",
      senior: "₹35-60 LPA",
    },
    growthPath: ["Senior PM", "Principal PM", "Director of Product", "VP of Product", "CEO"],
    workStyle: ["collaborative", "creative"],
    learningCurve: "moderate",
    remoteFreundly: true,
    whyTake: "Strategic impact, visible influence, good people skills leverage, stepping stone to exec roles.",
    challenges: "Constant stakeholder conflicts, own your failures but didn't code, meetings overdose, ambiguity.",
    cognitiveAlignment: ["Builder", "Analytical"],
  },

  {
    id: "product-designer",
    name: "Product Designer (UX/UI)",
    domain: "Product & Design",
    subdomain: "Design",
    description: "Design user experiences. Create interfaces that are beautiful, usable, and functional.",
    dailyWork: "Conduct user research, create wireframes/prototypes, design high-fidelity mockups, conduct usability testing, iterate based on feedback.",
    requiredSkills: [
      "UI/UX Design Principles",
      "Design Tools (Figma/XD)",
      "Prototyping",
      "User Research",
      "Communication",
    ],
    optionalSkills: [
      "Design Systems",
      "Accessibility (A11y)",
      "Motion Design",
      "Front-end Basics (HTML/CSS)",
      "Interaction Design",
    ],
    difficulty: "intermediate",
    demandLevel: "high",
    salaryRangeIndia: {
      junior: "₹4-7 LPA",
      mid: "₹11-18 LPA",
      senior: "₹25-45 LPA",
    },
    growthPath: ["Senior Designer", "Design Lead", "Design Manager", "Director of Design", "CPO"],
    workStyle: ["creative", "collaborative"],
    learningCurve: "moderate",
    remoteFreundly: true,
    whyTake: "Creative outlet, immediate visual feedback, end-users see your work, high growth demand.",
    challenges: "Design by committee, developer handoff friction, non-technical stakeholders = design death, feedback overload.",
    cognitiveAlignment: ["Creative", "Builder"],
  },

  {
    id: "design-systems-engineer",
    name: "Design Systems Engineer",
    domain: "Product & Design",
    subdomain: "Design",
    description: "Build and maintain design systems. Enable designers and engineers to work faster and maintain consistency.",
    dailyWork: "Design system architecture, maintain component libraries, documentation, tool integration, design + engineering collaboration.",
    requiredSkills: [
      "UI/UX Fundamentals",
      "Component Design",
      "Front-end (React/Vue)",
      "Design Tools",
      "Communication",
    ],
    optionalSkills: [
      "Design System Strategy",
      "Documentation",
      "Accessibility",
      "Typography Systems",
      "CSS Expertise",
    ],
    difficulty: "advanced",
    demandLevel: "high",
    salaryRangeIndia: {
      junior: "₹6-10 LPA",
      mid: "₹14-22 LPA",
      senior: "₹28-48 LPA",
    },
    growthPath: ["Senior Design Systems", "Design Systems Manager", "Design Lead", "Director of Design"],
    workStyle: ["systems", "collaborative"],
    learningCurve: "steep",
    remoteFreundly: true,
    whyTake: "Hybrid (design + code), force multiplier (help whole teams), scaling impact, emerging role.",
    challenges: "Broad skill set needed, politics (everyone wants their feature in system), perfectionism trap.",
    cognitiveAlignment: ["Systems", "Creative"],
  },

  {
    id: "ux-researcher",
    name: "UX Researcher",
    domain: "Product & Design",
    subdomain: "Research",
    description: "Understand users through research. Provide data-driven insights to inform design and product decisions.",
    dailyWork: "Conduct interviews, surveys, usability tests, analyze findings, create research reports, present insights, iterate designs.",
    requiredSkills: [
      "Research Methodologies (Qual/Quant)",
      "User Interview Skills",
      "Data Analysis",
      "Communication",
      "Statistics Basics",
    ],
    optionalSkills: [
      "Usability Testing",
      "Documentation",
      "Analytics Tools",
      "Design Thinking",
      "Prototyping",
    ],
    difficulty: "intermediate",
    demandLevel: "medium",
    salaryRangeIndia: {
      junior: "₹4-6 LPA",
      mid: "₹10-16 LPA",
      senior: "₹20-35 LPA",
    },
    growthPath: ["Senior Researcher", "Research Lead", "Research Manager", "Director of Research"],
    workStyle: ["analytical", "creative"],
    learningCurve: "moderate",
    remoteFreundly: true,
    whyTake: "User empathy focus, impact on product direction, research problems are interesting, emerging role.",
    challenges: "Insights not implemented (frustrating), slower iteration, research rigor vs business needs tension.",
    cognitiveAlignment: ["Analytical", "Creative"],
  },

  {
    id: "growth-product-manager",
    name: "Growth PM / Growth Manager",
    domain: "Product & Design",
    subdomain: "Product Management",
    description: "Drive user acquisition, activation, and retention. Focus on metrics and experimentation.",
    dailyWork: "Analyze user funnel, design growth experiments, run A/B tests, implement tracking, optimize onboarding, drive metrics.",
    requiredSkills: [
      "Analytics & Data",
      "A/B Testing & Experimentation",
      "Product Sense",
      "Communication",
      "SQL",
    ],
    optionalSkills: [
      "Marketing Fundamentals",
      "Python/R Analysis",
      "Cohort Analysis",
      "Product Development",
      "Business Acumen",
    ],
    difficulty: "intermediate",
    demandLevel: "high",
    salaryRangeIndia: {
      junior: "₹6-10 LPA",
      mid: "₹16-26 LPA",
      senior: "₹32-55 LPA",
    },
    growthPath: ["Senior Growth PM", "Head of Growth", "VP of Product", "Chief Growth Officer", "CEO"],
    workStyle: ["analytical", "collaborative"],
    learningCurve: "moderate",
    remoteFreundly: true,
    whyTake: "Directly tied to business metrics, high growth startups (equity upside), fast iteration, learning accelerated.",
    challenges: "Metrics obsession can harm experience, experimentation never ends, analyzing all this data is hard.",
    cognitiveAlignment: ["Analytical", "Builder"],
  },

  // ====== ADDITIONAL ROLES (8 roles) ======
  {
    id: "cloud-security-architect",
    name: "Cloud Security Architect",
    domain: "Cybersecurity",
    subdomain: "Cloud Infrastructure",
    description: "Design secure cloud infrastructure. Ensure compliance and protect cloud environments.",
    dailyWork: "Design security controls for cloud, perform cloud audits, manage identity & access, implement encryption, threat modeling.",
    requiredSkills: [
      "Cloud Platforms (AWS/Azure/GCP)",
      "Security Fundamentals",
      "Identity & Access Management",
      "Network Security",
      "Compliance",
    ],
    optionalSkills: [
      "Infrastructure-as-Code",
      "Container Security",
      "Incident Response",
      "Threat Modeling",
      "Cloud Certifications",
    ],
    difficulty: "advanced",
    demandLevel: "high",
    salaryRangeIndia: {
      junior: "N/A",
      mid: "₹22-35 LPA",
      senior: "₹45-80 LPA",
    },
    growthPath: ["Principal Cloud Security Architect", "VP of Security", "CISO"],
    workStyle: ["systems", "analytical"],
    learningCurve: "steep",
    remoteFreundly: true,
    whyTake: "Cloud + Security (hottest combo), high responsibility, excellent salary, every company migrates to cloud.",
    challenges: "5+ years experience needed, cloud landscape changes constantly, competing vendors' perspectives.",
    cognitiveAlignment: ["Systems", "Analytical"],
  },

  {
    id: "performance-engineer",
    name: "Performance Engineer",
    domain: "Software Engineering",
    subdomain: "Performance Optimization",
    description: "Optimize application performance. Make systems fast and efficient.",
    dailyWork: "Profile applications, identify bottlenecks, optimize code/databases, benchmark solutions, advise team.",
    requiredSkills: [
      "Performance Profiling Tools",
      "System Design",
      "Database Optimization",
      "Low-level Programming (C++/Go)",
      "Reverse Engineering",
    ],
    optionalSkills: [
      "Linux Kernel Basics",
      "Network Optimization",
      "GPU Programming",
      "Distributed Systems",
      "Mechanical Sympathy",
    ],
    difficulty: "advanced",
    demandLevel: "medium",
    salaryRangeIndia: {
      junior: "₹7-11 LPA",
      mid: "₹16-26 LPA",
      senior: "₹35-55 LPA",
    },
    growthPath: ["Senior Performance Engineer", "Performance Lead", "Principal Engineer", "CTO"],
    workStyle: ["analytical", "systems"],
    learningCurve: "steep",
    remoteFreundly: true,
    whyTake: "Deep technical work, system mastery, detective work is engaging, niche expertise.",
    challenges: "Narrow career path, optimization is never finished, micro-benchmarks can be futile.",
    cognitiveAlignment: ["Analytical", "Systems"],
  },

  {
    id: "tech-lead",
    name: "Tech Lead / Engineering Manager",
    domain: "Software Engineering",
    subdomain: "Leadership",
    description: "Lead engineering teams. Manage people, set direction, and drive technical excellence.",
    dailyWork: "1-on-1s with reports, code reviews, architecture decisions, performance evaluations, team planning, hiring, mentoring.",
    requiredSkills: [
      "Technical Expertise",
      "Leadership & Communication",
      "People Management",
      "System Design",
      "Decision Making",
    ],
    optionalSkills: [
      "Coaching Skills",
      "Budget Management",
      "Strategic Planning",
      "Organizational Dynamics",
      "Executive Communication",
    ],
    difficulty: "advanced",
    demandLevel: "high",
    salaryRangeIndia: {
      junior: "N/A",
      mid: "₹18-30 LPA",
      senior: "₹35-65 LPA",
    },
    growthPath: ["Engineering Manager", "Director of Engineering", "VP of Engineering", "CTO", "CEO"],
    workStyle: ["collaborative", "systems"],
    learningCurve: "steep",
    remoteFreundly: true,
    whyTake: "Leadership path, impact through people, strategic influence, higher salaries, stepping stone to exec.",
    challenges: "People management is hard, no more coding (sometimes), meetings overdose, people problems are complex.",
    cognitiveAlignment: ["Builder", "Systems"],
  },

  {
    id: "developer-advocate",
    name: "Developer Advocate",
    domain: "Product & Design",
    subdomain: "Developer Relations",
    description: "Advocate for developers. Build community, create content, and provide feedback to product.",
    dailyWork: "Create tutorials/documentation, present at conferences, build sample projects, gather developer feedback, support community.",
    requiredSkills: [
      "Technical Communication",
      "Software Development",
      "Public Speaking",
      "Content Creation",
      "Community Building",
    ],
    optionalSkills: [
      "Video Production",
      "Blogging/Writing",
      "Social Media",
      "Customer Empathy",
      "Product Insight",
    ],
    difficulty: "intermediate",
    demandLevel: "medium",
    salaryRangeIndia: {
      junior: "₹5-8 LPA",
      mid: "₹12-20 LPA",
      senior: "₹25-40 LPA",
    },
    growthPath: ["Senior Developer Advocate", "Developer Relations Lead", "VP of Developer Relations", "Head of Marketing"],
    workStyle: ["creative", "collaborative"],
    learningCurve: "moderate",
    remoteFreundly: true,
    whyTake: "Public speaking platform, community impact, less stressful than pure IC, flexible work.",
    challenges: "Not 'real engineering' perception, impact is hard to measure, content creation is exhausting.",
    cognitiveAlignment: ["Creative", "Builder"],
  },

  {
    id: "technical-writer",
    name: "Technical Writer",
    domain: "Product & Design",
    subdomain: "Documentation",
    description: "Create clear technical documentation. Help users and developers understand how to use products.",
    dailyWork: "Write API documentation, tutorials, guides, manage docs infrastructure, gather feedback, maintain documentation quality.",
    requiredSkills: [
      "Technical Writing",
      "Understanding Code",
      "Clarity & Grammar",
      "Tools (Markdown/Git)",
      "User Empathy",
    ],
    optionalSkills: [
      "Diagrams/Visualization",
      "Video Creation",
      "Developer Experience",
      "Content Management",
      "Technical Fundamentals",
    ],
    difficulty: "beginner",
    demandLevel: "medium",
    salaryRangeIndia: {
      junior: "₹3-5 LPA",
      mid: "₹8-13 LPA",
      senior: "₹16-28 LPA",
    },
    growthPath: ["Senior Technical Writer", "Documentation Lead", "Developer Relations", "Product Manager"],
    workStyle: ["creative", "collaborative"],
    learningCurve: "gradual",
    remoteFreundly: true,
    whyTake: "Creative writing outlet, help thousands of users, less stressful than engineering, good work-life balance.",
    challenges: "Not technical enough for some, documentation is never finished, impact is invisible.",
    cognitiveAlignment: ["Creative", "Builder"],
  },

  {
    id: "site-reliability-specialist",
    name: "Site Operations Engineer",
    domain: "Cloud & DevOps",
    subdomain: "Operations",
    description: "Manage production systems and infrastructure. Ensure systems are up and running.",
    dailyWork: "Monitor infrastructure, patch systems, manage capacity, handle incidents, perform maintenance, improve reliability.",
    requiredSkills: [
      "Linux/Windows Administration",
      "Networking",
      "System Monitoring",
      "Incident Management",
      "Scripting",
    ],
    optionalSkills: [
      "Cloud Platforms",
      "Automation",
      "Configuration Management",
      "Disaster Recovery",
      "Capacity Planning",
    ],
    difficulty: "intermediate",
    demandLevel: "medium",
    salaryRangeIndia: {
      junior: "₹4-6 LPA",
      mid: "₹10-16 LPA",
      senior: "₹20-35 LPA",
    },
    growthPath: ["Senior Site Ops", "Operations Lead", "Infrastructure Manager", "VP of Operations"],
    workStyle: ["systems", "analytical"],
    learningCurve: "moderate",
    remoteFreundly: false,
    whyTake: "Critical infrastructure work, hands-on learning, on-call pays well, career stability.",
    challenges: "On-call stress, repetitive tasks, legacy system complexity, on-call burnout.",
    cognitiveAlignment: ["Systems", "Analytical"],
  },

  {
    id: "qa-automation-engineer",
    name: "QA Automation Engineer",
    domain: "Software Engineering",
    subdomain: "Quality Assurance",
    description: "Build test automation frameworks. Scale testing through automation.",
    dailyWork: "Design test frameworks, write automated tests, maintain test infrastructure, improve test coverage, debug test failures.",
    requiredSkills: [
      "Test Automation Frameworks (Selenium/Cypress)",
      "Programming (Python/Java/JavaScript)",
      "Testing Fundamentals",
      "SQL",
      "CI/CD Integration",
    ],
    optionalSkills: [
      "BDD (Cucumber)",
      "Performance Testing",
      "API Testing",
      "Mobile Testing",
      "Advanced Programming",
    ],
    difficulty: "intermediate",
    demandLevel: "high",
    salaryRangeIndia: {
      junior: "₹4-6 LPA",
      mid: "₹10-16 LPA",
      senior: "₹20-35 LPA",
    },
    growthPath: ["Senior QA Automation", "QA Lead", "Engineering Manager", "Quality Director"],
    workStyle: ["analytical", "systems"],
    learningCurve: "moderate",
    remoteFreundly: true,
    whyTake: "Combines QA + coding, good scaling, high demand, less manual testing.",
    challenges: "'Brittle tests' are frustrating, sometimes seen as 'not real coding', test maintenance overhead.",
    cognitiveAlignment: ["Analytical", "Systems"],
  },
];

export function getAllRoles(): Role[] {
  return ROLES;
}

export function getRoleById(id: string): Role | undefined {
  return ROLES.find((role) => role.id === id);
}

export function getRolesByDomain(domain: string): Role[] {
  return ROLES.filter((role) => role.domain === domain);
}

export function getUniqueDomains(): string[] {
  return [...new Set(ROLES.map((role) => role.domain))];
}

export function searchRoles(query: string): Role[] {
  const lowerQuery = query.toLowerCase();
  return ROLES.filter(
    (role) =>
      role.name.toLowerCase().includes(lowerQuery) ||
      role.description.toLowerCase().includes(lowerQuery) ||
      role.requiredSkills.some((skill) =>
        skill.toLowerCase().includes(lowerQuery)
      )
  );
}

export function recommendRolesByCognitiveType(cognitiveType: CognitiveType): Role[] {
  return ROLES.filter((role) =>
    role.cognitiveAlignment.includes(cognitiveType)
  );
}

export function filterRolesByDifficulty(
  roles: Role[],
  difficulty: DifficultyLevel
): Role[] {
  return roles.filter((role) => role.difficulty === difficulty);
}

export function filterRolesByDemand(
  roles: Role[],
  demandLevel: DemandLevel
): Role[] {
  return roles.filter((role) => role.demandLevel === demandLevel);
}
