import { NextRequest } from 'next/server'
import { prisma } from '@/lib/prisma'
import { getAuthSession, unauthorized, success, serverError, badRequest } from '@/lib/api-auth'
import { nanoid } from 'nanoid'

// GET /api/proof — Get user's proof artifacts
export async function GET() {
  try {
    const session = await getAuthSession()
    if (!session?.user?.id) return unauthorized()

    const artifacts = await prisma.proofArtifact.findMany({
      where: { userId: session.user.id },
      orderBy: { createdAt: 'desc' },
    })

    return success(artifacts.map(a => ({
      ...a,
      skills: JSON.parse(a.skills || '[]'),
    })))
  } catch (error) {
    console.error('Proof GET error:', error)
    return serverError()
  }
}

// POST /api/proof — Generate proof artifact from a lab submission
export async function POST(req: NextRequest) {
  try {
    const session = await getAuthSession()
    if (!session?.user?.id) return unauthorized()

    const body = await req.json()
    const { submissionId, artifactType, title, description, isPublic } = body

    // If generating from a lab submission
    if (submissionId) {
      const submission = await prisma.labSubmission.findUnique({
        where: { id: submissionId },
        include: { task: true, evaluation: true },
      })

      if (!submission || submission.userId !== session.user.id) {
        return badRequest('Submission not found or unauthorized')
      }

      const taskSkills = JSON.parse(submission.task.skills || '[]')

      // Generate proof content
      const content = [
        `# Execution Proof: ${submission.task.title}`,
        ``,
        `## Task Context`,
        `- **Type**: ${submission.task.taskType}`,
        `- **Domain**: ${submission.task.domain}`,
        `- **Difficulty**: ${submission.task.difficulty}/10`,
        `- **Time Spent**: ${submission.timeSpentMin} minutes`,
        ``,
        `## Solution`,
        `\`\`\``,
        submission.submittedCode || 'N/A',
        `\`\`\``,
        ``,
        `## Approach & Reasoning`,
        submission.approach || 'Not provided',
        ``,
        `## Evaluation Results`,
        submission.evaluation ? [
          `- **Overall Score**: ${submission.evaluation.overallScore}/100`,
          `- **Correctness**: ${submission.evaluation.correctnessScore}%`,
          `- **Code Quality**: ${submission.evaluation.codeQualityScore}%`,
          `- **Efficiency**: ${submission.evaluation.efficiencyScore}%`,
          `- **Creativity**: ${submission.evaluation.creativityScore}%`,
          `- **Clarity**: ${submission.evaluation.clarityScore}%`,
        ].join('\n') : 'Pending evaluation',
        ``,
        `## Mentor Insights`,
        submission.evaluation?.technicalMentorFeedback || '',
        submission.evaluation?.strategyMentorFeedback || '',
        ``,
        `---`,
        `*Generated by Twinstitute AI Proof Engine*`,
        `*Verified execution trace — ${new Date().toISOString()}*`,
      ].join('\n')

      // Recruiter summary
      const recruiterSummary = `Demonstrated ${submission.task.taskType} capability in ${submission.task.domain}. ` +
        `Scored ${submission.evaluation?.overallScore || 'N/A'}/100 on a difficulty ${submission.task.difficulty}/10 task. ` +
        `Skills demonstrated: ${taskSkills.join(', ')}.`

      const artifact = await prisma.proofArtifact.create({
        data: {
          userId: session.user.id,
          artifactType: artifactType || 'execution_trace',
          title: title || `Proof: ${submission.task.title}`,
          description: description || submission.task.description,
          content,
          skills: JSON.stringify(taskSkills),
          labSubmissionId: submissionId,
          recruiterSummary,
          capabilityLevel: submission.evaluation?.overallScore
            ? submission.evaluation.overallScore >= 80 ? 'Advanced' : submission.evaluation.overallScore >= 60 ? 'Intermediate' : 'Foundation'
            : null,
          isPublic: isPublic || false,
          shareToken: isPublic ? nanoid(16) : null,
        },
      })

      return success({
        ...artifact,
        skills: JSON.parse(artifact.skills || '[]'),
      })
    }

    // Manual proof artifact creation
    if (!artifactType || !title || !description) {
      return badRequest('Required: artifactType, title, description (or submissionId)')
    }

    const artifact = await prisma.proofArtifact.create({
      data: {
        userId: session.user.id,
        artifactType,
        title,
        description,
        content: body.content || '',
        skills: JSON.stringify(body.skills || []),
        isPublic: isPublic || false,
        shareToken: isPublic ? nanoid(16) : null,
      },
    })

    return success({
      ...artifact,
      skills: JSON.parse(artifact.skills || '[]'),
    })
  } catch (error) {
    console.error('Proof POST error:', error)
    return serverError()
  }
}
