import Groq from "groq-sdk";
import {
  RoadmapModule,
  RoadmapPhase,
  RoleRoadmapStructure,
  getTimeAdaptation,
  getExpectedHours,
} from "./roadmap-structure";
import { generateRoleStructure } from "./role-roadmap-engine";

/**
 * HYBRID ROADMAP GENERATOR
 * 
 * Structure: Dynamic per role (generated by AI or cached), deterministic, IDENTICAL for all durations
 * Enhancement: AI-powered task generation
 * Time Adaptation: Multipliers only (hours + task density)
 * 
 * NEW: Now supports ANY job role (unlimited roles, not just 10-12 hardcoded)
 */

export interface GeneratedRoadmapModule extends RoadmapModule {
  estimatedHours: number; // Adapted hours for duration
  aiEnhancedTasks: string[]; // AI-generated tasks for this duration
}

export interface GeneratedRoadmapPhase extends RoadmapPhase {
  modules: GeneratedRoadmapModule[];
}

export interface GeneratedRoadmap {
  role: string;
  durationMonths: number;
  intensity: string;
  totalModules: number;
  totalHours: number;
  expectedHours: number;
  phases: GeneratedRoadmapPhase[];
  reasoning: string;
}

interface RoadmapGenerationInput {
  role: string;
  userSkills: string[];
  durationMonths: number;
}

// ═══════════════════════════════════════════════════════════════════
// 🔐 GROQ CLIENT
// ═══════════════════════════════════════════════════════════════════

function getGroqClient(): Groq | null {
  const apiKey = process.env.GROQ_ROADMAP_KEY;
  if (!apiKey) {
    console.warn("⚠️ GROQ_ROADMAP_KEY not set");
    return null;
  }

  try {
    return new Groq({ apiKey });
  } catch (error) {
    console.error("❌ Failed to create Groq client:", error);
    return null;
  }
}

// ═══════════════════════════════════════════════════════════════════
// 🛡️ ROBUST JSON PARSER
// ═══════════════════════════════════════════════════════════════════

function parseGroqJSON(response: string): any {
  try {
    return JSON.parse(response);
  } catch (e1) {
    // Try extracting from markdown
    const mdMatch = response.match(/```(?:json)?\s*(\{[\s\S]*?\})\s*```/);
    if (mdMatch) {
      try {
        return JSON.parse(mdMatch[1]);
      } catch (e2) {
        // Continue
      }
    }

    // Try finding JSON object
    const jsonStart = response.indexOf("{");
    const jsonEnd = response.lastIndexOf("}");

    if (jsonStart !== -1 && jsonEnd > jsonStart) {
      try {
        return JSON.parse(response.substring(jsonStart, jsonEnd + 1));
      } catch (e3) {
        console.error("❌ All JSON parsing attempts failed");
        throw e1;
      }
    }

    throw e1;
  }
}

// ═══════════════════════════════════════════════════════════════════
// 🤖 AI ENHANCEMENT: Batch generate tasks for multiple modules
// (Reduces API calls from 20 to ~5, avoiding rate limits)
// ═══════════════════════════════════════════════════════════════════

interface ModuleTaskRequest {
  module: RoadmapModule;
  taskCount: number;
}

interface ModuleTasksResponse {
  moduleTitles: string[];
  tasks: Record<string, string[]>; // Map of module title to task array
}

async function generateBatchTasks(
  moduleBatch: ModuleTaskRequest[],
  role: string,
  durationMonths: number
): Promise<Record<string, string[]>> {
  const groqClient = getGroqClient();

  // Fallback if Groq not available
  if (!groqClient) {
    console.log(`📌 Groq unavailable, using placeholder tasks`);
    const result: Record<string, string[]> = {};
    for (const { module, taskCount } of moduleBatch) {
      result[module.title] = Array(taskCount)
        .fill(0)
        .map((_, i) => `${module.title} - Task ${i + 1}`);
    }
    return result;
  }

  try {
    const intensity = getTimeAdaptation(durationMonths);
    
    // Build module descriptions
    const moduleDescriptions = moduleBatch
      .map(({ module, taskCount }) => 
        `- "${module.title}" (${taskCount} tasks): ${module.coreTopics.slice(0, 3).join(", ")}`
      )
      .join("\n");

    const prompt = `You are a curriculum designer. Generate specific tasks for multiple modules.

Role: ${role}
Duration: ${durationMonths} months (${intensity.intensityLabel})

Modules needing tasks:
${moduleDescriptions}

Generate a JSON object where each key is a module title and the value is an array of tasks:
{
  "Development Environment Setup": ["Task 1", "Task 2", "Task 3", "Task 4"],
  "JavaScript Fundamentals": ["Task 1", "Task 2", "Task 3", "Task 4"],
  "Web Fundamentals (HTTP, HTML, CSS)": ["Task 1", "Task 2", "Task 3", "Task 4"]
}

Requirements:
1. Each task must be specific, measurable, and actionable
2. Tasks should be practical (e.g., "Build a login component with React hooks")
3. Use exact module titles as keys
4. Each module should have the correct number of tasks
5. Adjust difficulty for ${durationMonths}-month duration
6. Return ONLY valid JSON, no markdown, no explanations`;

    console.log(`🤖 Batch generating tasks for ${moduleBatch.length} modules`);

    const message = await groqClient.chat.completions.create({
      model: "llama-3.3-70b-versatile",
      max_tokens: 2000,
      temperature: 0.6,
      messages: [{ role: "user", content: prompt }],
    });

    const responseText = message.choices?.[0]?.message?.content || "";

    if (!responseText) {
      throw new Error("Empty response");
    }

    const parsed = parseGroqJSON(responseText);

    if (typeof parsed !== "object" || parsed === null) {
      throw new Error("Response is not an object");
    }

    // Validate and normalize response
    const result: Record<string, string[]> = {};
    for (const { module, taskCount } of moduleBatch) {
      const tasks = parsed[module.title];
      if (Array.isArray(tasks) && tasks.length > 0) {
        result[module.title] = tasks
          .filter((t: any) => typeof t === "string")
          .slice(0, taskCount);
      } else {
        // Fallback if this module's tasks weren't generated
        result[module.title] = Array(taskCount)
          .fill(0)
          .map((_, i) => `${module.title} - Task ${i + 1}`);
      }
    }

    return result;
  } catch (error) {
    console.error(`⚠️ Batch task generation failed:`, error instanceof Error ? error.message : error);
    
    // Fallback: return placeholder tasks for all modules
    const result: Record<string, string[]> = {};
    for (const { module, taskCount } of moduleBatch) {
      result[module.title] = Array(taskCount)
        .fill(0)
        .map((_, i) => `${module.title} - Task ${i + 1}`);
    }
    return result;
  }
}

// ═══════════════════════════════════════════════════════════════════
// 👤 PERSONALIZATION: Mark user's existing skills
// ═══════════════════════════════════════════════════════════════════

function checkUserHasSkill(moduleSkills: string[], userSkills: string[]): boolean {
  const userSkillsLower = userSkills.map((s) => s.toLowerCase());
  return moduleSkills.some((skill) => userSkillsLower.includes(skill.toLowerCase()));
}

// ═══════════════════════════════════════════════════════════════════
// 🎓 MAIN FUNCTION: Generate roadmap with dynamic role structure + AI enhancement
// ═══════════════════════════════════════════════════════════════════

export async function generateRoadmap(
  input: RoadmapGenerationInput
): Promise<GeneratedRoadmap> {
  const { role, userSkills, durationMonths } = input;

  console.log(
    `\n📍 [ROADMAP] Generating for: ${role} (${durationMonths}m)\n`
  );

  // Generate or get cached role structure (supports ANY role)
  let baseStructure: RoleRoadmapStructure;
  try {
    baseStructure = await generateRoleStructure(role);
    console.log(`✅ [ROLES] Using dynamically generated structure for "${role}"`);
  } catch (error) {
    console.error(`❌ Failed to generate role structure:`, error);
    throw new Error(`Unable to generate roadmap structure for role: ${role}`);
  }

  const timeAdaptation = getTimeAdaptation(durationMonths);
  const expectedHours = getExpectedHours(durationMonths);

  let totalHours = 0;

  // Collect ALL modules for batch task generation
  const allModules: { module: RoadmapModule; phase: RoadmapPhase }[] = [];
  baseStructure.phases.forEach((phase) => {
    phase.modules.forEach((module) => {
      allModules.push({ module, phase });
    });
  });

  // Batch generate tasks for all modules (4 per batch to avoid rate limits)
  const BATCH_SIZE = 4;
  const batchRequests: ModuleTaskRequest[] = allModules.map(({ module }) => ({
    module,
    taskCount: timeAdaptation.tasksPerModule,
  }));

  console.log(`📦 Batching task generation: ${batchRequests.length} modules in ${Math.ceil(batchRequests.length / BATCH_SIZE)} batches`);

  const allTasksMap: Record<string, string[]> = {};

  // Process batches sequentially with small delay to avoid rate limits
  for (let i = 0; i < batchRequests.length; i += BATCH_SIZE) {
    const batch = batchRequests.slice(i, i + BATCH_SIZE);
    console.log(`  📦 Processing batch ${Math.floor(i / BATCH_SIZE) + 1} of ${Math.ceil(batchRequests.length / BATCH_SIZE)}`);
    
    const batchTasks = await generateBatchTasks(batch, role, durationMonths);
    Object.assign(allTasksMap, batchTasks);

    // Small delay between batches to stay under rate limit
    if (i + BATCH_SIZE < batchRequests.length) {
      await new Promise((resolve) => setTimeout(resolve, 1000)); // 1 second delay
    }
  }

  // Generate phases with time-adapted modules
  const generatedPhases: GeneratedRoadmapPhase[] = baseStructure.phases.map((phase) => {
    const generatedModules: GeneratedRoadmapModule[] = phase.modules.map((module) => {
      const estimatedHours = Math.round(module.baseHours * timeAdaptation.multiplier);
      totalHours += estimatedHours;

      return {
        ...module,
        estimatedHours,
        aiEnhancedTasks: allTasksMap[module.title] || Array(timeAdaptation.tasksPerModule)
          .fill(0)
          .map((_, i) => `${module.title} - Task ${i + 1}`),
        userHasSkill: checkUserHasSkill(module.skills, userSkills),
      };
    });

    return {
      ...phase,
      modules: generatedModules,
    };
  });

  const result: GeneratedRoadmap = {
    role: baseStructure.role,
    durationMonths,
    intensity: timeAdaptation.intensityLabel,
    totalModules: baseStructure.totalModules,
    totalHours,
    expectedHours,
    phases: generatedPhases,
    reasoning: `This ${durationMonths}-month ${role} roadmap covers ${baseStructure.totalModules} modules across 4 capability layers: Foundation, Core Skills, Application, and Mastery. Expected hours: ${expectedHours} (actual: ${totalHours}). ${
      durationMonths === 12
        ? "Comprehensive mastery program with deep expertise in all areas."
        : durationMonths === 6
        ? "Balanced learning with solid fundamentals and real-world application."
        : durationMonths === 3
        ? "Focused curriculum excluding advanced topics, suitable for career transition."
        : "Intensive boot camp covering essentials for job readiness."
    }`,
  };

  console.log(`✅ [ROADMAP] Generated: ${baseStructure.totalModules} modules, ${totalHours} hours (target: ${expectedHours})`);
  console.log(`   Phases: ${generatedPhases.map((p) => `${p.phase} (${p.modules.length})`).join(", ")}`);

  return result;
}
